# Generated by Django 6.0.1 on 2026-01-16 15:09

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reservaciones', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='reservacion',
            name='estado_pago',
            field=models.CharField(choices=[('pendiente', 'Pendiente'), ('procesando', 'Procesando'), ('pagado', 'Pagado'), ('fallido', 'Fallido'), ('reembolsado', 'Reembolsado')], default='pendiente', max_length=20),
        ),
        migrations.AddField(
            model_name='reservacion',
            name='fecha_pago',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='reservacion',
            name='metodo_pago',
            field=models.CharField(blank=True, help_text='Tarjeta, PayPhone, etc.', max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='reservacion',
            name='referencia_pago',
            field=models.CharField(blank=True, help_text='Referencia del pago', max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='reservacion',
            name='transaccion_id',
            field=models.CharField(blank=True, help_text='ID de la transacción en la pasarela', max_length=255, null=True),
        ),
        migrations.AddIndex(
            model_name='reservacion',
            index=models.Index(fields=['transaccion_id'], name='reservacion_transac_b09d71_idx'),
        ),
    ]
